#!/usr/bin/env python3
"""Convert PNG/BMP images in src/assets/ to C++ header arrays for M5GFX.

This script converts image files to 1-bit packed byte arrays suitable for
M5GFX's drawBitmap function. It can run standalone or as a PlatformIO pre-build script.

Usage:
    python convert_icons.py              # Run standalone
    Add to platformio.ini as pre script  # Run during build
"""

import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: PIL/Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

ICON_SIZE = 64


def get_project_root():
    """Get project root, works both standalone and in PlatformIO."""
    # When run as PlatformIO extra script, env is available
    try:
        from SCons.Script import Import
        Import("env")
        # Get project directory from PlatformIO environment
        return Path(env.subst("$PROJECT_DIR"))
    except Exception:
        pass

    # Standalone: walk up from script location
    script_path = Path(__file__).resolve() if '__file__' in dir() else Path(os.getcwd())
    if script_path.is_file():
        script_path = script_path.parent

    # Find project root by looking for platformio.ini
    current = script_path
    while current != current.parent:
        if (current / "platformio.ini").exists():
            return current
        current = current.parent

    # Fallback to current working directory
    return Path(os.getcwd())


def image_to_bytes(img_path: Path) -> list:
    """Convert image to 1-bit packed bytes for M5GFX drawBitmap.

    M5GFX expects MSB-first packed bits where 1 = foreground (black).
    Each row is packed into ICON_SIZE/8 bytes.
    """
    img = Image.open(img_path).convert('L')  # Convert to grayscale first
    img = img.resize((ICON_SIZE, ICON_SIZE), Image.Resampling.LANCZOS)

    # Convert to 1-bit: pixels darker than 128 become 1 (black/foreground)
    pixels = list(img.getdata())

    bytes_out = []
    for row in range(ICON_SIZE):
        for byte_idx in range(ICON_SIZE // 8):
            byte = 0
            for bit in range(8):
                px_idx = row * ICON_SIZE + byte_idx * 8 + bit
                # Black pixels (dark) = 1, white pixels (light) = 0
                if pixels[px_idx] < 128:
                    byte |= (0x80 >> bit)
            bytes_out.append(byte)
    return bytes_out


def generate_header(icons: list) -> str:
    """Generate the C++ header file content."""
    lines = [
        "#pragma once",
        "// Auto-generated by tools/icons/convert_icons.py",
        "// Do not edit manually - regenerate from source images",
        "",
        "#include <cstdint>",
        "",
        f"inline constexpr int16_t GENERATED_ICON_SIZE = {ICON_SIZE};",
        "",
    ]

    for name, data in icons:
        lines.append(f"// {name} icon ({ICON_SIZE}x{ICON_SIZE}, 1-bit)")
        lines.append(f"inline constexpr uint8_t ICON_{name}[] = {{")

        # Format bytes in rows of 16
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            lines.append(f"    {hex_str},")

        lines.append("};")
        lines.append("")

    return "\n".join(lines)


def main(project_root: Path = None):
    """Main entry point."""
    if project_root is None:
        project_root = get_project_root()

    assets_dir = project_root / "src" / "assets"
    output_file = assets_dir / "icons_generated.hpp"

    if not assets_dir.exists():
        print(f"ERROR: Assets directory not found: {assets_dir}")
        return 1

    icons = []
    image_extensions = ('.png', '.bmp', '.jpg', '.jpeg')

    for f in sorted(assets_dir.iterdir()):
        if f.suffix.lower() in image_extensions:
            # Convert filename to C++ constant name
            # e.g., "MTG.bmp" -> "MTG", "my-icon.png" -> "MY_ICON"
            name = f.stem.upper().replace('-', '_').replace(' ', '_')

            print(f"Converting {f.name} -> ICON_{name}")
            try:
                data = image_to_bytes(f)
                icons.append((name, data))
            except Exception as e:
                print(f"  ERROR: Failed to convert {f.name}: {e}")
                continue

    if not icons:
        print("No icons found to convert")
        # Still generate an empty header to avoid build errors
        output_file.write_text("#pragma once\n// No icons generated\n")
        return 0

    header_content = generate_header(icons)
    output_file.write_text(header_content)

    print(f"Generated {len(icons)} icon(s) to {output_file.relative_to(project_root)}")
    return 0


# Check if running as PlatformIO extra script
try:
    from SCons.Script import Import
    Import("env")
    # Running in PlatformIO build context
    project_dir = Path(env.subst("$PROJECT_DIR"))
    main(project_dir)
except Exception:
    # Running standalone
    if __name__ == "__main__":
        sys.exit(main())
